### ISSUE TITLE
"Unhandled Exception: Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly" for referenced package assembly.

### ISSUE THREAD

**Issue by Arbixal** [lucaslorentz/minicover#43] opened 2018-03-08 00:23 UTC
I was attempting to instrument code coverage for my persistence tests using:
`dotnet minicover instrument --assemblies bin/**/*.dll --sources "../Persistence/**/*.cs"`

It resulted in the following output:
```
Instrumenting assembly "Persistence"
Instrumenting assembly "Persistence"
Instrumenting assembly "Persistence"

Unhandled Exception: Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'Nest, Version=6.0.0.0, Culture=neutral, PublicKeyToken=96c599bbe3e70f5d
'
   at Mono.Cecil.BaseAssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
   at Mono.Cecil.DefaultAssemblyResolver.Resolve(AssemblyNameReference name)
   at Mono.Cecil.MetadataResolver.Resolve(TypeReference type)
   at Mono.Cecil.Mixin.CheckedResolve(TypeReference self)
   at Mono.Cecil.MetadataBuilder.GetConstantType(TypeReference constant_type, Object constant)
   at Mono.Cecil.MetadataBuilder.AddConstant(IConstantProvider owner, TypeReference type)
   at Mono.Cecil.MetadataBuilder.AddField(FieldDefinition field)
   at Mono.Cecil.MetadataBuilder.AddFields(TypeDefinition type)
   at Mono.Cecil.MetadataBuilder.AddType(TypeDefinition type)
   at Mono.Cecil.MetadataBuilder.AddTypes()
   at Mono.Cecil.MetadataBuilder.BuildTypes()
   at Mono.Cecil.MetadataBuilder.BuildModule()
   at Mono.Cecil.MetadataBuilder.BuildMetadata()
   at Mono.Cecil.ModuleWriter.<>c.<BuildMetadata>b__2_0(MetadataBuilder builder, MetadataReader _)
   at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func`3 read)
   at Mono.Cecil.ModuleWriter.BuildMetadata(ModuleDefinition module, MetadataBuilder metadata)
   at Mono.Cecil.ModuleWriter.Write(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
   at Mono.Cecil.ModuleWriter.WriteModule(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
   at Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters)
   at MiniCover.Instrumentation.Instrumenter.InstrumentAssemblyIfNecessary(String assemblyFile)
   at MiniCover.Instrumentation.Instrumenter.VisitAssemblyGroup(IEnumerable`1 assemblyFiles)
   at MiniCover.Instrumentation.Instrumenter.Execute()
   at MiniCover.Program.<>c__DisplayClass0_0.<Main>b__1()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at MiniCover.Program.Main(String[] args)
```

I believe it is related to #6, but the assembly it needs is not in my bin directory, it is instead a referenced nuget package.

**Comment by lucaslorentz** [comment] 2018-03-08 20:22
Yes, I guess we would need to implement a custom assembly loader for Cecil that finds the assemblies.

Can you share a sample project with the issue?
I tried to reproduce the issue some time ago and it's very hard, it seems that Cecil only tries to load the assemblies if you reference them in specific ways.

**Comment by lucaslorentz** [comment] 2018-03-08 20:27
I think the files `ASSEMBLY.deps.json` and `ASSEMLBY.runtimeconfig.dev.json` can be read to decide where to load the assemblies. We need to check the .NET Core loader logic to do something similar.

**Comment by laskoviymishka** [comment] 2018-04-26 11:46
I face same issue, but was able to workaraund it by adding
```
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
```
to my *Tests.csproj files

**Comment by lucaslorentz** [comment] 2018-06-14 22:21
@laskoviymishka 
Can you share the project where you faced that issue?

**Comment by laskoviymishka** [comment] 2018-06-15 07:40
Sorry it in private repository. But i was able to calculate coverage after copy local lock file assemblies.

Test.csproj file is something like that
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>    
    <TargetFramework>netcoreapp2.0</TargetFramework>    
    <PostBuildEvent></PostBuildEvent>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>full</DebugType>
    <DebugSymbols>True</DebugSymbols>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Pricings\Samples\sample_rule.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="altcover" Version="3.0.444" />
    <PackageReference Include="coverlet.msbuild" Version="1.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.TestHost" Version="2.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="2.0.2" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.7.0" />
    <PackageReference Include="Moq" Version="4.8.2" />
    <PackageReference Include="MSTest.TestAdapter" Version="1.2.1" />
    <PackageReference Include="MSTest.TestFramework" Version="1.2.1" />
    <PackageReference Include="xunit" Version="2.3.1" />
    <PackageReference Include="xunit.extensibility.execution" Version="2.3.1" />
    <PackageReference Include="xunit.runner.console" Version="2.3.1" />
    <PackageReference Include="xunit.runner.reporters" Version="2.3.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.3.1" />
    <DotNetCliToolReference Include="MiniCover" Version="2.0.0-ci-20180328123752" />
    <DotNetCliToolReference Include="dotnet-xunit" Version="2.3.1" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Pricings\**\*.json" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Api\Api.csproj" />
    <ProjectReference Include="..\BusinessComponents\BusinessComponents.csproj" />
    <ProjectReference Include="..\BusinessEntities\BusinessEntities.csproj" />
    <ProjectReference Include="..\DataAccess\DataAccess.csproj" />
    <ProjectReference Include="..\Domain\Domain.csproj" />
    <ProjectReference Include="..\Pricing\.Pricing.csproj" />
    <ProjectReference Include="..\ServiceAgents\ServiceAgents.csproj" />
  </ItemGroup>

    <None Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="log4net.config">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
```

**Comment by laskoviymishka** [comment] 2018-07-05 20:37
it works thx

**Comment by lucaslorentz** [comment] 2018-07-05 21:42
Closing as it seems to be fixed.
@Arbixal, please re-open if it still fails for you.

**Closed by lucaslorentz** 2018-07-05 21:42 UTC
